# MySQL
#   gem 'mysql2'
# PostgreSQL
#   gem 'pg'
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: bookstore_development

test:
  <<: *default
  database: bookstore_test

production:
  <<: *default
  database: bookstore_production
  username: bookstore
  password: <%= ENV['BOOKSTORE_DATABASE_PASSWORD'] %>
